### ISSUE TITLE
Cannot run the module

### ISSUE THREAD

**Issue by bibile** [baekgaard/peyetribe#2]
Hi,

Nice module!
I use Python 2.7.5 under windows seven.
Got an error line 180:
self._timestamp = int(ts.strftime("%s")) + int(ts.strftime("%f"))/1000000.0 

```
Traceback (most recent call last):
  File "peyetribe.py", line 565, in next
    return EyeTribe.Frame(p['values']['frame'])
  File "peyetribe.py", line 180, in __init__
    self._timestamp = int(ts.strftime("%s")) + int(ts.strftime("%f"))/1000000.0
ValueError: Invalid format string
```

I had to change %s to %S to have it working.
%s does not seems to be a possible format:
https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior

**Comment by baekgaard** [comment]
Thanks for the feedback! I also just had a student reporting the same issue just a few days ago too (also in windows), but have not had time to fix it yet, sorry! Will fix it shortly; for some reason the Mac libraries I was using apparently accepted the '%s' as seconds too...

**Comment by bibile** [comment]
Great! Blocking bug, but easy to fix :)

Another thing I changed while using your module is to keep the json dict in the Frame object contructor:

```
self._json = json
```

Sometimes, could be nice to access or store it in a json format.

I was also wondering why you embed Coord, Frame, Calibration and CalibrationPoint classes in EyeTribe ?
Is there an advantage in doing it that way ?

Thanks again for your module!

**Comment by baekgaard** [comment]
I've fixed the bug now. The "%s" is only implemented on *nix based machines, it looks. It returns seconds since epoch start (i.e. Jan 1st, 1970) and assumes local time. Using "%S" will not work, as it only returns the seconds part of the date time, so it will roll over at 59 and back to 0; hence it's been fixed in a better way (I hope).

I've also added the _json "by popular request", and a getter method (json) to retrieve this properly (there is no setter method).

The Coord, Frame, etc are embedded inside the EyeTribe class to avoid cluttering the upper level namespace, so it's more of a "data encapsulation" decision than anything else. Guess my C++ background might draw too strong shadows into the Python code too :-)

Let me know if this works for you and then I'll close this issue.

Thanks again for reporting!

**Comment by bibile** [comment]
Perfect! It works. (sorry for a late reply).

I do not think that you need to embed Coord, Frame, .... in Eytribe class. They are already in your file peyetribe.py
It's a namespace.

if you do: import peyetribe
then, everything could be:
    peyetribe.EyeTribe
    peyetribe.Coord
    peyetribe.Frame

But I probably did not do enough C++
I would have access directly all the properties without getter and setter too :)

Thanks for sharing your code.
